### ISSUE TITLE
SubscriptionTopic pydantic model doesn't require the `status` attribute when it should

### ISSUE THREAD

**Issue by ryancausey** [trycourier/courier-python#73] opened 2024-05-01 02:45 UTC
I was able to create a `SubscriptionTopic` pydantic model instance with only the `id` argument set, but this is not accepted by the `create_or_replace` API for the Tenants client:

```python
from courier import DefaultPreferences, SubscriptionTopic
from courier import Client
client = Courier(authorization_token="******")
client.tenants.create_or_replace(tenant_id="org_asdf", name="foobaz")

client.tenants.create_or_replace(
    tenant_id="org_asdf",
    name="foobaz",
    default_preferences=DefaultPreferences(items=[SubscriptionTopic(id="foo")])
)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/rccausey/.cache/pypoetry/virtualenvs/notifications-api-6mUc-8uv-py3.11/lib/python3.11/site-packages/courier/tenants/client.py", line 117, in create_or_replace
    raise BadRequestError(pydantic_v1.parse_obj_as(BadRequest, _response.json()))  # type: ignore
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
courier.commons.errors.bad_request_error.BadRequestError: status_code: 400, body: message='[{"error":"/default_preferences/items/0 must have required property \'status\'","path":"/default_preferences/items/0"}]' type='invalid_request_error'
```

The create or replace API docs specify that the `status` field is required for a `SubscriptionTopic`: https://www.courier.com/docs/reference/tenants/create-replace/

The Pydantic model should be updated to require the `status` field so it matches the REST API.

This was observed while using trycourier = "6.0.2".

**Comment by dsinghvi** [comment] 2024-05-01 02:52
@ryancausey thanks for reporting this issue, it looks like the pydantic model does have a [required field for status](https://github.com/trycourier/courier-python/blob/88090df59843f1bb4c0e4cf4a069c4790bedb404/src/courier/tenants/types/subscription_topic.py#L17). This will take a little more time to root cause since I would have expected Pydantic to throw a validation error here!

**Comment by ryancausey** [comment] 2024-05-01 02:54
Yeah, it's weird. It doesn't complain:

```python
$ poetry run python
Python 3.11.4 (main, Jul 20 2023, 18:33:17) [GCC 11.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from courier import DefaultPreferences, SubscriptionTopic
>>> SubscriptionTopic(id="foo")
SubscriptionTopic(id='foo', status=None)
>>>
```

**Comment by dsinghvi** [comment] 2024-05-01 02:57
Found the issue here, we model the enums as `SubscriptionTopicStatus = typing.Union[typing.Literal["OPTED_OUT", "OPTED_IN", "REQUIRED"], typing.Any]`. This is to make sure that newly introduced enum values do not break pydantic / legacy SDKs. 

There's an intentional reason behind choosing `typing.Any` instead of `str` I believe, so we'll get back to you here!

**Comment by dsinghvi** [comment] 2024-05-23 13:25
@ryancausey closing this issue for now; while the typing isn't ideal the enum is intentionally generated this way!

**Closed by dsinghvi** 2024-05-23 13:25 UTC
